version: "2.4"

services:
  postgres:
    restart: always
    container_name: db-postgres
    ports:
      - "25432:5432"
    environment:
      POSTGRES_PASSWORD: password
#      POSTGRES_USER: user
#      POSTGRES_DB: postgres
    volumes:
      - ./postgres/data:/home/user/data
    build:
      context: ./
      dockerfile: ./postgres/Dockerfile
    networks:
      zaymigo:
        aliases:
          - bki-service-db
      db-postgres:
        aliases:
          - postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - "2580:8080"
    networks:
      db-postgres:
        aliases:
          - adminer
networks:
  zaymigo:
    external: true
    name: zaymigo
  db-postgres:
    name: "db-postgres"
